#!/bin/bash

#=================================================================
# runValgrind
#
# @author: Kush Patel
# @description: Program to run a C++ program on each test in the
#   test suite and reports on any tests which causes the program
#   to have a memory error
# @version: 1.4 25/09/2014
#=================================================================

if [ $# -ne 2 ]; then
   echo "incorrect number of command line arguments" >&2
   exit 1
fi

cat $1 | while read nextLine; do
    if [ ! -r "$nextLine.in" ]; then
       echo "file not found" >&2
       exit 1
    fi
       output=`valgrind --log-fd=1 --leak-check=full --show-reachable=yes $2 < $nextLine.in`
       errorCheck=`echo "$output" | tail -1 | egrep -c '.*ERROR SUMMARY: [1-9]* .'`
       if [ $errorCheck -eq 1 ]; then
          echo "Memory leak detected: $nextLine.in"
          echo "$output"
       fi
done
